// constants.ts
import type { Society } from './types';

// --- App Defaults ---
export const DEFAULT_CURRENCY = 'CAD';
export const DEFAULT_MAX_CLASSES = 14;

// --- Supabase Config Defaults (Optional) ---
// Keys are managed in the Settings tab via localStorage, but defaults can be set here if needed for env vars.
// Setting them here makes the app pre-populate the credentials so they don't need to be entered manually each time.
export const SUPABASE_URL = 'https://hxgojapfsqsmwveaszvn.supabase.co';
export const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4Z29qYXBmc3FzbXd2ZWFzenZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMyMTU5MTUsImV4cCI6MjA3ODc5MTkxNX0.smrff1lRtkK9E0SroEf7TUhpyTHPc6S9InK0vJjqs_8';

// --- Canada Mission Societies Directory ---
export const CANADA_MISSION_SOCIETIES: Society[] = [
    {
        id: 'gmct',
        name: 'Ghana Methodist Church Toronto',
        shortName: 'GMCT',
        societyCode: 'GMCT',
        city: 'Toronto',
        province: 'Ontario',
        provinceCode: 'ON',
        isPrimary: true,
        address: '69 Milvan Drive, North York, ON M9L 1Y8',
        description: 'Main Head Society & Mission Headquarters',
        accentColor: 'indigo',
        features: {
            wesleyHall: true,
            parking: true,
            etransfers: true,
            requisitions: true,
            harvest: true,
            harvestPledges: true,
            developmentFund: true,
            taxReceipts: true,
            assets: true,
            organizationFunds: true,
            dayBorn: true,
            childrensMinistry: true,
        },
    },
    {
        id: 'ebenezer-hamilton',
        name: 'Ebenezer Methodist Society',
        shortName: 'Ebenezer',
        societyCode: 'EBEN-HAM',
        city: 'Hamilton',
        province: 'Ontario',
        provinceCode: 'ON',
        accentColor: 'blue',
        description: 'Canada Mission - Hamilton Parish',
        features: {
            wesleyHall: false,
            parking: false,
            etransfers: true,
            requisitions: true,
            harvest: true,
            harvestPledges: true,
            developmentFund: true,
            taxReceipts: true,
            assets: true,
            organizationFunds: true,
            dayBorn: true,
            childrensMinistry: true,
        },
    },
    {
        id: 'redemption-etobicoke',
        name: 'Redemption Methodist Society',
        shortName: 'Redemption',
        societyCode: 'RED-ETOB',
        city: 'Etobicoke',
        province: 'Ontario',
        provinceCode: 'ON',
        accentColor: 'amber',
        description: 'Canada Mission - Etobicoke Parish',
        features: {
            wesleyHall: false,
            parking: false,
            etransfers: true,
            requisitions: true,
            harvest: true,
            harvestPledges: true,
            developmentFund: true,
            taxReceipts: true,
            assets: true,
            organizationFunds: true,
            dayBorn: true,
            childrensMinistry: true,
        },
    },
    {
        id: 'bethany-brampton',
        name: 'Bethany Methodist Society',
        shortName: 'Bethany',
        societyCode: 'BETH-BRAM',
        city: 'Brampton',
        province: 'Ontario',
        provinceCode: 'ON',
        accentColor: 'purple',
        description: 'Canada Mission - Brampton Parish',
        features: {
            wesleyHall: false,
            parking: false,
            etransfers: true,
            requisitions: true,
            harvest: true,
            harvestPledges: true,
            developmentFund: true,
            taxReceipts: true,
            assets: true,
            organizationFunds: true,
            dayBorn: true,
            childrensMinistry: true,
        },
    },
    {
        id: 'mt-zion-london',
        name: 'Mt. Zion Methodist Society',
        shortName: 'Mt. Zion',
        societyCode: 'MTZ-LON',
        city: 'London',
        province: 'Ontario',
        provinceCode: 'ON',
        accentColor: 'teal',
        description: 'Canada Mission - London Parish',
        features: {
            wesleyHall: false,
            parking: false,
            etransfers: true,
            requisitions: true,
            harvest: true,
            harvestPledges: true,
            developmentFund: true,
            taxReceipts: true,
            assets: true,
            organizationFunds: true,
            dayBorn: true,
            childrensMinistry: true,
        },
    },
    {
        id: 'wesley-thunderbay',
        name: 'Wesley Methodist Society',
        shortName: 'Wesley (Thunder Bay)',
        societyCode: 'WES-TBAY',
        city: 'Thunder Bay',
        province: 'Ontario',
        provinceCode: 'ON',
        accentColor: 'sky',
        description: 'Canada Mission - Thunder Bay Parish',
        features: {
            wesleyHall: false,
            parking: false,
            etransfers: true,
            requisitions: true,
            harvest: true,
            harvestPledges: true,
            developmentFund: true,
            taxReceipts: true,
            assets: true,
            organizationFunds: true,
            dayBorn: true,
            childrensMinistry: true,
        },
    },
    {
        id: 'bethel-calgary',
        name: 'Bethel Methodist Society',
        shortName: 'Bethel (Calgary)',
        societyCode: 'BETH-CAL',
        city: 'Calgary',
        province: 'Alberta',
        provinceCode: 'AB',
        accentColor: 'rose',
        description: 'Canada Mission - Calgary Parish',
        features: {
            wesleyHall: false,
            parking: false,
            etransfers: true,
            requisitions: true,
            harvest: true,
            harvestPledges: true,
            developmentFund: true,
            taxReceipts: true,
            assets: true,
            organizationFunds: true,
            dayBorn: true,
            childrensMinistry: true,
        },
    },
    {
        id: 'wesley-edmonton',
        name: 'Wesley Methodist Society',
        shortName: 'Wesley (Edmonton)',
        societyCode: 'WES-EDM',
        city: 'Edmonton',
        province: 'Alberta',
        provinceCode: 'AB',
        accentColor: 'emerald',
        description: 'Canada Mission - Edmonton Parish',
        features: {
            wesleyHall: false,
            parking: false,
            etransfers: true,
            requisitions: true,
            harvest: true,
            harvestPledges: true,
            developmentFund: true,
            taxReceipts: true,
            assets: true,
            organizationFunds: true,
            dayBorn: true,
            childrensMinistry: true,
        },
    },
    {
        id: 'peniel-vancouver',
        name: 'Peniel Methodist Society',
        shortName: 'Peniel',
        societyCode: 'PEN-VAN',
        city: 'Vancouver',
        province: 'British Columbia',
        provinceCode: 'BC',
        accentColor: 'cyan',
        description: 'Canada Mission - Vancouver Parish',
        features: {
            wesleyHall: false,
            parking: false,
            etransfers: true,
            requisitions: true,
            harvest: true,
            harvestPledges: true,
            developmentFund: true,
            taxReceipts: true,
            assets: true,
            organizationFunds: true,
            dayBorn: true,
            childrensMinistry: true,
        },
    },
    {
        id: 'zion-vancouver',
        name: 'Zion Methodist Society',
        shortName: 'Zion',
        societyCode: 'ZION-VAN',
        city: 'Vancouver',
        province: 'British Columbia',
        provinceCode: 'BC',
        accentColor: 'violet',
        description: 'Canada Mission - Vancouver Parish',
        features: {
            wesleyHall: false,
            parking: false,
            etransfers: true,
            requisitions: true,
            harvest: true,
            harvestPledges: true,
            developmentFund: true,
            taxReceipts: true,
            assets: true,
            organizationFunds: true,
            dayBorn: true,
            childrensMinistry: true,
        },
    },
    {
        id: 'bethel-winnipeg',
        name: 'Bethel Methodist Society',
        shortName: 'Bethel (Winnipeg)',
        societyCode: 'BETH-WPG',
        city: 'Winnipeg',
        province: 'Manitoba',
        provinceCode: 'MB',
        accentColor: 'fuchsia',
        description: 'Canada Mission - Winnipeg Parish',
        features: {
            wesleyHall: false,
            parking: false,
            etransfers: true,
            requisitions: true,
            harvest: true,
            harvestPledges: true,
            developmentFund: true,
            taxReceipts: true,
            assets: true,
            organizationFunds: true,
            dayBorn: true,
            childrensMinistry: true,
        },
    },
    {
        id: 'halifax-ns',
        name: 'Halifax Methodist Society',
        shortName: 'Halifax',
        societyCode: 'HAL-NS',
        city: 'Halifax',
        province: 'Nova Scotia',
        provinceCode: 'NS',
        accentColor: 'orange',
        description: 'Canada Mission - Halifax Parish',
        features: {
            wesleyHall: false,
            parking: false,
            etransfers: true,
            requisitions: true,
            harvest: true,
            harvestPledges: true,
            developmentFund: true,
            taxReceipts: true,
            assets: true,
            organizationFunds: true,
            dayBorn: true,
            childrensMinistry: true,
        },
    },
    {
        id: 'stjohns-newfoundland',
        name: "St. John's Methodist Society",
        shortName: "St. John's",
        societyCode: 'STJ-NL',
        city: "St. John's",
        province: 'Newfoundland and Labrador',
        provinceCode: 'NL',
        accentColor: 'rose',
        description: "Canada Mission - St. John's Parish",
        features: {
            wesleyHall: false,
            parking: false,
            etransfers: true,
            requisitions: true,
            harvest: true,
            harvestPledges: true,
            developmentFund: true,
            taxReceipts: true,
            assets: true,
            organizationFunds: true,
            dayBorn: true,
            childrensMinistry: true,
        },
    },
];

export const DEFAULT_SOCIETY = CANADA_MISSION_SOCIETIES[0]; // GMCT is default primary
