import jsPDF from 'jspdf';
import type { Entry, Member, Settings } from '../types';
import { formatMethod } from '../utils';

interface ReceiptData {
    entry: Entry;
    member: Member | undefined;
    settings: Settings;
}

export const generateReceipt = ({ entry, member, settings }: ReceiptData) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    
    // Header
    doc.setFillColor(139, 92, 246); // Purple
    doc.rect(0, 0, pageWidth, 40, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('GMCT', pageWidth / 2, 20, { align: 'center' });
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('Contribution Receipt', pageWidth / 2, 30, { align: 'center' });
    
    // Receipt Details
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    
    let yPos = 55;
    
    // Receipt Number
    doc.setFont('helvetica', 'bold');
    doc.text('Receipt No:', 20, yPos);
    doc.setFont('helvetica', 'normal');
    doc.text(entry.id.substring(0, 8).toUpperCase(), 80, yPos);
    
    yPos += 10;
    doc.setFont('helvetica', 'bold');
    doc.text('Date:', 20, yPos);
    doc.setFont('helvetica', 'normal');
    // Parse date string (YYYY-MM-DD) as local date to avoid timezone shift
    const [year, month, day] = entry.date.split('-');
    const dateObj = new Date(parseInt(year), parseInt(month) - 1, parseInt(day));
    doc.text(dateObj.toLocaleDateString('en-US', { 
        year: 'numeric', 
        month: 'long', 
        day: 'numeric' 
    }), 80, yPos);
    
    // Member Information Section
    yPos += 20;
    doc.setFillColor(240, 240, 255);
    doc.rect(15, yPos - 5, pageWidth - 30, 50, 'F');
    
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text('Member Information', 20, yPos + 5);
    
    doc.setFontSize(10);
    yPos += 15;
    
    doc.setFont('helvetica', 'bold');
    doc.text('Name:', 20, yPos);
    doc.setFont('helvetica', 'normal');
    doc.text(entry.memberName || 'N/A', 80, yPos);
    
    yPos += 10;
    doc.setFont('helvetica', 'bold');
    doc.text('Member #:', 20, yPos);
    doc.setFont('helvetica', 'normal');
    doc.text(member?.memberNumber?.toString() || 'N/A', 80, yPos);
    
    yPos += 10;
    doc.setFont('helvetica', 'bold');
    doc.text('Class:', 20, yPos);
    doc.setFont('helvetica', 'normal');
    doc.text(entry.classNumber?.toString() || member?.classNumber?.toString() || 'N/A', 80, yPos);
    
    // Contribution Details Section
    yPos += 25;
    doc.setFillColor(255, 245, 235);
    doc.rect(15, yPos - 5, pageWidth - 30, 60, 'F');
    
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text('Contribution Details', 20, yPos + 5);
    
    doc.setFontSize(10);
    yPos += 15;
    
    doc.setFont('helvetica', 'bold');
    doc.text('Type:', 20, yPos);
    doc.setFont('helvetica', 'normal');
    const typeDisplay = entry.type.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
    doc.text(typeDisplay, 80, yPos);
    
    yPos += 10;
    doc.setFont('helvetica', 'bold');
    doc.text('Description:', 20, yPos);
    doc.setFont('helvetica', 'normal');
    doc.text(entry.note || 'Development Fund Contribution', 80, yPos);
    
    yPos += 10;
    doc.setFont('helvetica', 'bold');
    doc.text('Amount Paid:', 20, yPos);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(22, 163, 74); // Green
    doc.text(`${settings.currency} ${entry.amount.toFixed(2)}`, 80, yPos);
    
    // Payment Method
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    yPos += 10;
    doc.setFont('helvetica', 'bold');
    doc.text('Payment Method:', 20, yPos);
    doc.setFont('helvetica', 'normal');
    doc.text(formatMethod(entry.method), 80, yPos);
    
    // Footer
    yPos = doc.internal.pageSize.getHeight() - 40;
    doc.setDrawColor(200, 200, 200);
    doc.line(20, yPos, pageWidth - 20, yPos);
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(100, 100, 100);
    yPos += 10;
    doc.text('Thank you for your contribution!', pageWidth / 2, yPos, { align: 'center' });
    
    yPos += 7;
    doc.text('This is an official receipt generated by GMCT Management System', pageWidth / 2, yPos, { align: 'center' });
    
    yPos += 7;
    doc.setFontSize(8);
    doc.setTextColor(200, 0, 0); // Red for disclaimer
    doc.setFont('helvetica', 'bold');
    doc.text('Disclaimer: For record purpose only - Not for tax purposes', pageWidth / 2, yPos, { align: 'center' });
    
    yPos += 7;
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated: ${new Date().toLocaleString()}`, pageWidth / 2, yPos, { align: 'center' });
    
    return doc;
};

export const downloadReceipt = ({ entry, member, settings }: ReceiptData) => {
    try {
        console.log('downloadReceipt called with:', { entry, member, settings });
        if (!entry) {
            throw new Error('Entry data is missing');
        }
        if (!settings) {
            throw new Error('Settings data is missing');
        }
        const doc = generateReceipt({ entry, member, settings });
        const fileName = `Receipt_${entry.memberName.replace(/\s+/g, '_')}_${entry.date}_${entry.id.substring(0, 8)}.pdf`;
        console.log('Attempting to save file:', fileName);
        doc.save(fileName);
        console.log('Receipt saved successfully');
        return { success: true, message: 'Receipt downloaded successfully!' };
    } catch (error) {
        const errorMessage = error instanceof Error ? error.message : String(error);
        console.error('Error generating receipt:', errorMessage);
        return { success: false, message: `Failed to generate receipt: ${errorMessage}` };
    }
};

export const shareViaWhatsApp = ({ entry, member, settings }: ReceiptData) => {
    try {
        console.log('shareViaWhatsApp called with:', { entry, member, settings });
        if (!entry) {
            throw new Error('Entry data is missing');
        }
        if (!settings) {
            throw new Error('Settings data is missing');
        }
        
        // Generate the PDF
        const doc = generateReceipt({ entry, member, settings });
        const fileName = `Receipt_${entry.memberName.replace(/\s+/g, '_')}_${entry.date}_${entry.id.substring(0, 8)}.pdf`;
        
        // For WhatsApp sharing on desktop/web, we trigger a download
        // and open a WhatsApp message to notify the user to share the file
        console.log('Generating PDF for WhatsApp share:', fileName);
        doc.save(fileName);
        
        // Also prepare a message for the user
        const receiptText = `*GMCT Contribution Receipt*\n\n` +
            `Receipt No: ${entry.id.substring(0, 8).toUpperCase()}\n` +
            `Member: ${entry.memberName}\n` +
            `Amount: ${settings.currency} ${entry.amount.toFixed(2)}\n\n` +
            `The receipt PDF (${fileName}) has been downloaded. You can now share it via WhatsApp.`;
        
        console.log('Opening WhatsApp with share message');
        const whatsappUrl = `https://wa.me/?text=${encodeURIComponent(receiptText)}`;
        window.open(whatsappUrl, '_blank');
        
        return { success: true, message: 'Receipt downloaded! WhatsApp opening to share...' };
    } catch (error) {
        const errorMessage = error instanceof Error ? error.message : String(error);
        console.error('Error sharing via WhatsApp:', errorMessage);
        return { success: false, message: `Failed to share via WhatsApp: ${errorMessage}` };
    }
};

export const shareReceipt = async ({ entry, member, settings }: ReceiptData) => {
    const doc = generateReceipt({ entry, member, settings });
    const pdfBlob = doc.output('blob');
    const fileName = `Receipt_${entry.memberName.replace(/\s+/g, '_')}_${entry.date}.pdf`;
    
    if (navigator.share) {
        const file = new File([pdfBlob], fileName, { type: 'application/pdf' });
        const canShare = navigator.canShare && navigator.canShare({ files: [file] });
        if (canShare) {
            try {
                await navigator.share({
                    files: [file],
                    title: 'Contribution Receipt',
                    text: `Receipt for ${entry.memberName} - ${settings.currency} ${entry.amount.toFixed(2)}`
                });
                return;
            } catch (error) {
                console.error('Error sharing:', error);
            }
        }
    }
    // Fallback to download if sharing not supported
    downloadReceipt({ entry, member, settings });
};
